#!/bin/sh

uci set system.@system[0].hostname='GWRT'
uci set system.@system[0].zonename='Asia/Shanghai'
uci set system.@system[0].timezone='CST-8'
uci set network.lan.ipaddr=192.168.10.1
uci commit system
/etc/init.d/system restart
